apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: icebot

spec:
  serviceName: minio
  replicas: 1

  selector:
    matchLabels:
      app: minio

  template:
    metadata:
      labels:
        app: minio

    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          imagePullPolicy: IfNotPresent

          args:
            - server
            - /data
            - --console-address
            - ":9001"

          ports:
            - name: api
              containerPort: 9000

            - name: console
              containerPort: 9001

          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: icebot-env
                  key: MINIO_ROOT_USER

            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icebot-env
                  key: MINIO_ROOT_PASSWORD

          volumeMounts:
            - name: minio-data
              mountPath: /data

          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: "1"
              memory: 768Mi

  volumeClaimTemplates:
    - metadata:
        name: minio-data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: local-path

        resources:
          requests:
            storage: 20Gi
