apiVersion: batch/v1
kind: Job
metadata:
  name: icebot-db-migration
  namespace: icebot

spec:
  backoffLimit: 1

  template:
    metadata:
      labels:
        app: icebot-db-migration

    spec:
      restartPolicy: Never

      imagePullSecrets:
        - name: ghcr-pull-secret

      containers:
        - name: migration
          image: ghcr.io/su26se092-icecream-arm-robot/icebot-backend:14606e8e91f81ede490211d57815195a5c868a42
          imagePullPolicy: IfNotPresent

          command:
            - /app/efbundle

          env:
            - name: ConnectionStrings__IceBot_DB
              valueFrom:
                secretKeyRef:
                  name: icebot-env
                  key: DB_CONNECTION_STRING
