apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icebot-keyring
  namespace: icebot

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 256Mi
